# Generated by Django 5.2.17 on 2026-09-09 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=250)),
                ('release_date', models.DateField(db_index=True)),
                ('rating', models.DecimalField(db_index=True, decimal_places=1, default=0, max_digits=3)),
                ('popularity', models.PositiveIntegerField(db_index=True, default=0)),
                ('description', models.TextField(blank=True)),
                ('poster_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.genre')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='movies.language')),
            ],
            options={
                'ordering': ['-popularity', '-rating'],
            },
        ),
        migrations.CreateModel(
            name='RecentlyViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_views', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed_movies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_time', models.DateTimeField(db_index=True)),
                ('ticket_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='movies.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_bookings', to=settings.AUTH_USER_MODEL)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movies.show')),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('total_seats', models.PositiveIntegerField(default=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='theaters', to='movies.city')),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='movies.theater'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['release_date', 'rating'], name='movie_release_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['popularity', 'rating'], name='movie_pop_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='recentlyviewed',
            index=models.Index(fields=['user', 'viewed_at'], name='view_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='recentlyviewed',
            index=models.Index(fields=['movie', 'viewed_at'], name='view_movie_date_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'booked_at'], name='booking_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['show', 'booked_at'], name='booking_show_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='theater',
            constraint=models.UniqueConstraint(fields=('name', 'city'), name='unique_theater_city'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['movie', 'show_time'], name='show_movie_time_idx'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['theater', 'show_time'], name='show_theater_time_idx'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['ticket_price', 'show_time'], name='show_price_time_idx'),
        ),
    ]
