# Generated by Django 5.2.17 on 2026-08-27 12:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('theater_name', models.CharField(max_length=200)),
                ('show_time', models.DateTimeField()),
                ('total_seats', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)])),
                ('ticket_price', models.DecimalField(decimal_places=2, default=200, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeatReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('BOOKED', 'Booked'), ('RELEASED', 'Released')], default='RESERVED', max_length=20)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('reserved_until', models.DateTimeField(blank=True, null=True)),
                ('booked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_reservations', to=settings.AUTH_USER_MODEL)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_reservations', to='seats.show')),
            ],
            options={
                'ordering': ['seat_number'],
                'constraints': [models.UniqueConstraint(fields=('show', 'seat_number'), name='unique_seat_per_show')],
            },
        ),
    ]
